---
kind: pipeline
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: flake8
  pull: always
  image: python:3.7
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - flake8 ./ansibledoctor
  environment:
    PY_COLORS: 1

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: python35-pytest
  pull: always
  image: python:3.5
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - ansible-doctor --help
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python36-pytest
  pull: always
  image: python:3.6
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - ansible-doctor --help
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python37-pytest
  pull: always
  image: python:3.7
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - ansible-doctor --help
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python38-rc-pytest
  pull: always
  image: python:3.8-rc
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - ansible-doctor --help
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

depends_on:
- lint

---
kind: pipeline
name: security

platform:
  os: linux
  arch: amd64

steps:
- name: bandit
  pull: always
  image: python:3.7
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - bandit -r ./ansibledoctor -x ./ansibledoctor/tests
  environment:
    PY_COLORS: 1

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

depends_on:
- test

---
kind: pipeline
name: build-package

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: python:3.7
  commands:
  - python setup.py sdist bdist_wheel

- name: checksum
  pull: always
  image: alpine
  commands:
  - "cd dist/ && sha256sum * > sha256sum.txt"

- name: publish-github
  pull: always
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - "dist/*"
    - sha256sum.txt
    note: CHANGELOG.md
    overwrite: true
    title: "${DRONE_TAG}"
  when:
    ref:
    - "refs/tags/**"

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

depends_on:
- security

---
kind: pipeline
name: build-container-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: python:3.7
  commands:
  - python setup.py bdist_wheel

- name: dryrun
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: xoxys/ansible-doctor
    username:
      from_secret: docker_username

- name: publish
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    auto_tag: true
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: xoxys/ansible-doctor
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - "refs/tags/**"

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

depends_on:
- security

---
kind: pipeline
name: build-container-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  pull: always
  image: python:3.7
  commands:
  - python setup.py bdist_wheel

- name: dryrun
  pull: always
  image: plugins/docker:linux-arm64
  settings:
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: xoxys/ansible-doctor
    username:
      from_secret: docker_username

- name: publish
  pull: always
  image: plugins/docker:linux-arm64
  settings:
    auto_tag: true
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: xoxys/ansible-doctor
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - "refs/tags/**"

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

depends_on:
- security

---
kind: pipeline
name: build-container-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  pull: always
  image: python:3.7
  commands:
  - python setup.py bdist_wheel

- name: dryrun
  pull: always
  image: plugins/docker:linux-arm
  settings:
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: xoxys/ansible-doctor
    username:
      from_secret: docker_username

- name: publish
  pull: always
  image: plugins/docker:linux-arm
  settings:
    auto_tag: true
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: xoxys/ansible-doctor
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - "refs/tags/**"

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

depends_on:
- security

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: matrix
  image: plugins/matrix
  settings:
    homeserver:
      from_secret: matrix_homeserver
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    template: "Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message: {{ build.message }}"
    username:
      from_secret: matrix_username

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  status:
  - success
  - failure

depends_on:
- build-package
- build-container-amd64
- build-container-arm64
- build-container-arm

---
kind: signature
hmac: 2db6ebb30be1f686e852ed208db770c956667f430738007d007380eaa81cab82

...
